### ISSUE TITLE
提供几本缺失的书：《文革的政治与困境：陈伯达与「造反」的时代》、《陈伯达遗稿:狱中自述及其他》

### ISSUE THREAD

**Issue by monthlyliaoyuan** [PirateBook1/history#2]
“研究类”中，“白承旭，《文革的政治与困境：陈伯达与「造反」的时代》”这本书在Z-library上是有的，只是需要用繁体搜索才找得到。
有两个版本，[一个是文字版pdf，6MB](https://zh.singlelogin.re/book/5580339/61ff2f/%E6%96%87%E9%9D%A9%E7%9A%84%E6%94%BF%E6%B2%BB%E8%88%87%E5%9B%B0%E5%A2%83%E9%99%B3%E4%BC%AF%E9%81%94%E8%88%87%E9%80%A0%E5%8F%8D%E7%9A%84%E6%99%82%E4%BB%A3.html)；
[另一个大概是影印版pdf，62.82 MB](https://zh.singlelogin.re/book/5610200/45dba6/%E6%96%87%E9%9D%A9%E7%9A%84%E6%94%BF%E6%B2%BB%E8%88%87%E5%9B%B0%E5%A2%83-%E9%99%B3%E4%BC%AF%E9%81%94%E8%88%87%E9%80%A0%E5%8F%8D%E7%9A%84%E6%99%82%E4%BB%A3-wen-ge-de-zheng-zhi-yu-kun-jing-chen-bo-da-yu-zao-fan-de-shi-dai.html)。

![屏幕截图 2024-02-17 163023](https://github.com/PirateBook1/history/assets/132804597/d176b618-ceb6-4509-bd4f-0e09b1f210a6)

“回忆录&传记”中，“陈伯达，《陈伯达狱中文稿》”没在Z-library里找到，但是有一本[内蒙古人民出版社的《陈伯达遗稿:狱中自述及其他》](https://zh.singlelogin.re/book/26200568/2f5b60/%E9%99%88%E4%BC%AF%E8%BE%BE%E9%81%97%E7%A8%BF%E7%8B%B1%E4%B8%AD%E8%87%AA%E8%BF%B0%E5%8F%8A%E5%85%B6%E4%BB%96.html)。

![Screenshot 2024-02-17 at 17-44-04 陈伯达遗稿 狱中自述及其他 陈伯达 download on Z-Library](https://github.com/PirateBook1/history/assets/132804597/518fbc94-bc67-426c-a052-1c41c42ffa58)

**Comment by PirateBook1** [comment]
已收到，感谢
